In [19]:
from create_env_gs import (make_env, run_q_gridsearch, run_pi_gs, run_vi_gs)
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from gymnasium.spaces import Tuple, Discrete

seed = 123
np.random.seed(seed)

$$
\textbf{Frozen Lake}
$$

In [20]:
mdp_fl = 'FrozenLake8x8-v1'
size_fl = 16
is_slippery_fl = True
render_mode_fl = 'ansi'
prob_frozen_fl = 0.9
ep_steps_fl = 400

In [21]:
frozenlake = make_env(mdp=mdp_fl, 
                      size=size_fl, 
                      slip=is_slippery_fl,
                      render=render_mode_fl,
                      prob_frozen=prob_frozen_fl,
                      seed=seed,
                      ep_steps=ep_steps_fl)


SFFFFFHFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFHFFFFFFFFH
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFHFFFFFFHFFFF
FFFFFFFFFFFFFFFF
FFFFFFFHHFFFHHFF
FFFFFFHFFFFFFFHF
FFFFFFFFFFFFFFFF
FFFFFFFHFFFFFFHF
FFFFFFFFFFFFHFFF
FFFFFFFFFFFHFFFF
FFFFFFFFFFFFFHFH
HFFFFFFFFFFFFHFF
FFHFFFHFFFFFFFFG



In [22]:
gamma_q_fl = [0.90, 0.99, 0.999]
epsilon_decay_q_fl = [0.90, 0.99, 0.999]
iters_q_fl = [100000, 300000, 500000]

In [23]:
q_fl = run_q_gridsearch(process=frozenlake,
                        gamma=gamma_q_fl,
                        epsilon_decay=epsilon_decay_q_fl,
                        iters=iters_q_fl)

running q_learning with gamma: 0.9 epsilon decay: 0.9  iterations: 100000


/home/leonardo_leads/miniconda3/envs/mlmdp/lib/python3.12/site-packages/bettermdptools/algorithms/rl.py:178: UserWarning: Episode was truncated.  Bootstrapping 0 reward.
  warnings.warn("Episode was truncated.  Bootstrapping 0 reward.")


In [ ]:
q_fl.keys()

In [ ]:
#results_reward_one = {key: value for key, value in q_fl[(1.05, 1.0, 50000)].items()}

In [ ]:
# for key, value in q_fl[(1.05, 1.0, 50000)].items():
    # if key == 'average episode rewards':
    #     print(key, value)

In [ ]:
# q_fl[(1.05, 1.0, 50000)]

In [ ]:
gamma_p_fl = [0.90, 0.95, 0.99, 0.999]
theta_p_fl = [0.01, 0.001, .0001, 0.00001]
iters_p_fl = [100000, 400000, 700000, 1000000]

In [ ]:
fl_pi = run_pi_gs(process=frozenlake,
                  gamma=gamma_p_fl,
                  theta=theta_p_fl,
                  iters=iters_p_fl)

running PI with gamma: 0.9  n_iters: 100000  theta: 0.01
runtime = 0.15 seconds
Avg. episode reward:  0.8014665
###################

running PI with gamma: 0.9  n_iters: 100000  theta: 0.001


/home/leonardo_leads/miniconda3/envs/mlmdp/lib/python3.12/site-packages/gymnasium/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


runtime = 0.16 seconds
Avg. episode reward:  0.811679
###################

running PI with gamma: 0.9  n_iters: 100000  theta: 0.0001
runtime = 0.13 seconds
Avg. episode reward:  0.811679
###################

running PI with gamma: 0.9  n_iters: 100000  theta: 1e-05
runtime = 0.17 seconds
Avg. episode reward:  0.8625149999999999
###################

running PI with gamma: 0.9  n_iters: 400000  theta: 0.01
runtime = 0.14 seconds
Avg. episode reward:  0.8014665
###################

running PI with gamma: 0.9  n_iters: 400000  theta: 0.001
runtime = 0.16 seconds
Avg. episode reward:  0.811679
###################

running PI with gamma: 0.9  n_iters: 400000  theta: 0.0001
runtime = 0.14 seconds
Avg. episode reward:  0.811679
###################

running PI with gamma: 0.9  n_iters: 400000  theta: 1e-05
runtime = 0.18 seconds
Avg. episode reward:  0.8625149999999999
###################

running PI with gamma: 0.9  n_iters: 700000  theta: 0.01
runtime = 0.13 seconds
Avg. episode reward:  0.8

In [ ]:
fl_pi.keys()

dict_keys([(0.9, 100000, 0.01), (0.9, 100000, 0.001), (0.9, 100000, 0.0001), (0.9, 100000, 1e-05), (0.9, 400000, 0.01), (0.9, 400000, 0.001), (0.9, 400000, 0.0001), (0.9, 400000, 1e-05), (0.9, 700000, 0.01), (0.9, 700000, 0.001), (0.9, 700000, 0.0001), (0.9, 700000, 1e-05), (0.9, 1000000, 0.01), (0.9, 1000000, 0.001), (0.9, 1000000, 0.0001), (0.9, 1000000, 1e-05), (0.95, 100000, 0.01), (0.95, 100000, 0.001), (0.95, 100000, 0.0001), (0.95, 100000, 1e-05), (0.95, 400000, 0.01), (0.95, 400000, 0.001), (0.95, 400000, 0.0001), (0.95, 400000, 1e-05), (0.95, 700000, 0.01), (0.95, 700000, 0.001), (0.95, 700000, 0.0001), (0.95, 700000, 1e-05), (0.95, 1000000, 0.01), (0.95, 1000000, 0.001), (0.95, 1000000, 0.0001), (0.95, 1000000, 1e-05), (0.99, 100000, 0.01), (0.99, 100000, 0.001), (0.99, 100000, 0.0001), (0.99, 100000, 1e-05), (0.99, 400000, 0.01), (0.99, 400000, 0.001), (0.99, 400000, 0.0001), (0.99, 400000, 1e-05), (0.99, 700000, 0.01), (0.99, 700000, 0.001), (0.99, 700000, 0.0001), (0.99, 7

In [ ]:
gamma_v_fl = [0.90, 0.95, 0.99, 0.999]
theta_v_fl = [0.01, 0.001, .0001, 0.00001]
iters_v_fl = [100000, 400000, 700000, 1000000]

In [ ]:
fl_vi = run_vi_gs(process=frozenlake,
                  gamma=gamma_v_fl,
                  theta=theta_v_fl,
                  iters=iters_v_fl)

running VI with gamma: 0.9  n_iters: 100000  theta: 0.01
runtime = 0.03 seconds
Avg. episode reward:  -0.013396499999999947
###################

running VI with gamma: 0.9  n_iters: 100000  theta: 0.001
runtime = 0.06 seconds
Avg. episode reward:  -0.003358999999999946
###################

running VI with gamma: 0.9  n_iters: 100000  theta: 0.0001
runtime = 0.09 seconds
Avg. episode reward:  0.398001
###################

running VI with gamma: 0.9  n_iters: 100000  theta: 1e-05
runtime = 0.14 seconds
Avg. episode reward:  0.811679
###################

running VI with gamma: 0.9  n_iters: 400000  theta: 0.01
runtime = 0.02 seconds
Avg. episode reward:  -0.013396499999999947
###################

running VI with gamma: 0.9  n_iters: 400000  theta: 0.001
runtime = 0.05 seconds
Avg. episode reward:  -0.003358999999999946
###################

running VI with gamma: 0.9  n_iters: 400000  theta: 0.0001
runtime = 0.09 seconds
Avg. episode reward:  0.398001
###################

running VI with g

In [ ]:
fl_vi.keys()

dict_keys([(0.9, 100000, 0.0001), (0.9, 100000, 1e-05), (0.9, 400000, 0.0001), (0.9, 400000, 1e-05), (0.9, 700000, 0.0001), (0.9, 700000, 1e-05), (0.9, 1000000, 0.0001), (0.9, 1000000, 1e-05), (0.95, 100000, 0.001), (0.95, 100000, 0.0001), (0.95, 100000, 1e-05), (0.95, 400000, 0.001), (0.95, 400000, 0.0001), (0.95, 400000, 1e-05), (0.95, 700000, 0.001), (0.95, 700000, 0.0001), (0.95, 700000, 1e-05), (0.95, 1000000, 0.001), (0.95, 1000000, 0.0001), (0.95, 1000000, 1e-05), (0.99, 100000, 0.001), (0.99, 100000, 0.0001), (0.99, 100000, 1e-05), (0.99, 400000, 0.001), (0.99, 400000, 0.0001), (0.99, 400000, 1e-05), (0.99, 700000, 0.001), (0.99, 700000, 0.0001), (0.99, 700000, 1e-05), (0.99, 1000000, 0.001), (0.99, 1000000, 0.0001), (0.99, 1000000, 1e-05), (0.999, 100000, 0.01), (0.999, 100000, 0.001), (0.999, 100000, 0.0001), (0.999, 100000, 1e-05), (0.999, 400000, 0.01), (0.999, 400000, 0.001), (0.999, 400000, 0.0001), (0.999, 400000, 1e-05), (0.999, 700000, 0.01), (0.999, 700000, 0.001), (0

$$
\textbf{Blackjack}
$$

In [ ]:
mdp_bj = 'Blackjack-v1'
render_mode_bj = 'rgb_array'
size_bj = Tuple([Discrete(32), Discrete(11), Discrete(2)])
ep_steps_bj = 400

In [ ]:
blackjack = make_env(mdp=mdp_bj,
                     size=size_bj,
                     slip=None,
                     render=render_mode_bj,
                     seed=seed,
                     prob_frozen=None,
                     ep_steps=ep_steps_bj)


[[[ 7 99 36]
  [ 7 99 36]
  [ 7 99 36]
  ...
  [ 7 99 36]
  [ 7 99 36]
  [ 7 99 36]]

 [[ 7 99 36]
  [ 7 99 36]
  [ 7 99 36]
  ...
  [ 7 99 36]
  [ 7 99 36]
  [ 7 99 36]]

 [[ 7 99 36]
  [ 7 99 36]
  [ 7 99 36]
  ...
  [ 7 99 36]
  [ 7 99 36]
  [ 7 99 36]]

 ...

 [[ 7 99 36]
  [ 7 99 36]
  [ 7 99 36]
  ...
  [ 7 99 36]
  [ 7 99 36]
  [ 7 99 36]]

 [[ 7 99 36]
  [ 7 99 36]
  [ 7 99 36]
  ...
  [ 7 99 36]
  [ 7 99 36]
  [ 7 99 36]]

 [[ 7 99 36]
  [ 7 99 36]
  [ 7 99 36]
  ...
  [ 7 99 36]
  [ 7 99 36]
  [ 7 99 36]]]


In [ ]:
gamma_q_bj = [0.90, 0.99, 0.999]
epsilon_decay_q_bj = [0.90, 0.99, 0.999]
iters_q_bj = [100000, 300000, 500000]

In [ ]:
q_bj = run_q_gridsearch(process=blackjack,
                        gamma=gamma_q_bj,
                        epsilon_decay=epsilon_decay_q_bj,
                        iters=iters_q_bj)

In [ ]:
q_bj.keys()

In [ ]:
#results_reward_one = {key: value for key, value in q_bj[(1.05, 1.0, 50000)].items()}

In [ ]:
# for key, value in q_bj[(1.05, 1.0, 50000)].items():
    # if key == 'average episode rewards':
    #     print(key, value)

In [ ]:
# q_bj[(1.05, 1.0, 50000)]

In [ ]:
gamma_p_bj = [0.90, 0.95, 0.99, 0.999]
theta_p_bj = [0.01, 0.001, .0001, 0.00001]
iters_p_bj = [100000, 400000, 700000, 1000000]

In [ ]:
bj_pi = run_pi_gs(process=blackjack,
                  gamma=gamma_p_bj,
                  theta=theta_p_bj,
                  iters=iters_p_bj)

running PI with gamma: 0.9  n_iters: 100000  theta: 0.01
runtime = 0.04 seconds
Avg. episode reward:  -0.09
###################

running PI with gamma: 0.9  n_iters: 100000  theta: 0.001
runtime = 0.02 seconds
Avg. episode reward:  -0.09
###################

running PI with gamma: 0.9  n_iters: 100000  theta: 0.0001
runtime = 0.03 seconds
Avg. episode reward:  -0.09
###################

running PI with gamma: 0.9  n_iters: 100000  theta: 1e-05
runtime = 0.03 seconds
Avg. episode reward:  -0.09
###################

running PI with gamma: 0.9  n_iters: 400000  theta: 0.01
runtime = 0.02 seconds
Avg. episode reward:  -0.09
###################

running PI with gamma: 0.9  n_iters: 400000  theta: 0.001
runtime = 0.02 seconds
Avg. episode reward:  -0.09
###################

running PI with gamma: 0.9  n_iters: 400000  theta: 0.0001
runtime = 0.03 seconds
Avg. episode reward:  -0.09
###################

running PI with gamma: 0.9  n_iters: 400000  theta: 1e-05
runtime = 0.04 seconds
Avg. epis

In [ ]:
bj_pi.keys()

dict_keys([(0.9, 100000, 0.01), (0.9, 100000, 0.001), (0.9, 100000, 0.0001), (0.9, 100000, 1e-05), (0.9, 400000, 0.01), (0.9, 400000, 0.001), (0.9, 400000, 0.0001), (0.9, 400000, 1e-05), (0.9, 700000, 0.01), (0.9, 700000, 0.001), (0.9, 700000, 0.0001), (0.9, 700000, 1e-05), (0.9, 1000000, 0.01), (0.9, 1000000, 0.001), (0.9, 1000000, 0.0001), (0.9, 1000000, 1e-05), (0.95, 100000, 0.01), (0.95, 100000, 0.001), (0.95, 100000, 0.0001), (0.95, 100000, 1e-05), (0.95, 400000, 0.01), (0.95, 400000, 0.001), (0.95, 400000, 0.0001), (0.95, 400000, 1e-05), (0.95, 700000, 0.01), (0.95, 700000, 0.001), (0.95, 700000, 0.0001), (0.95, 700000, 1e-05), (0.95, 1000000, 0.01), (0.95, 1000000, 0.001), (0.95, 1000000, 0.0001), (0.95, 1000000, 1e-05), (0.99, 100000, 0.01), (0.99, 100000, 0.001), (0.99, 100000, 0.0001), (0.99, 100000, 1e-05), (0.99, 400000, 0.01), (0.99, 400000, 0.001), (0.99, 400000, 0.0001), (0.99, 400000, 1e-05), (0.99, 700000, 0.01), (0.99, 700000, 0.001), (0.99, 700000, 0.0001), (0.99, 7

In [ ]:
gamma_v_bj = [0.90, 0.95, 0.99, 0.999]
theta_v_bj = [0.01, 0.001, .0001, 0.00001]
iters_v_bj = [100000, 400000, 700000, 1000000]

In [ ]:
bj_vi = run_vi_gs(process=blackjack,
                  gamma=gamma_v_bj,
                  theta=theta_v_bj,
                  iters=iters_v_bj)

running VI with gamma: 0.9  n_iters: 100000  theta: 0.01
runtime = 0.01 seconds
in bj****************************
Avg. episode reward:  -0.09
###################

running VI with gamma: 0.9  n_iters: 100000  theta: 0.001
runtime = 0.01 seconds
in bj****************************
Avg. episode reward:  -0.09
###################

running VI with gamma: 0.9  n_iters: 100000  theta: 0.0001
runtime = 0.03 seconds
in bj****************************
Avg. episode reward:  -0.09
###################

running VI with gamma: 0.9  n_iters: 100000  theta: 1e-05
runtime = 0.03 seconds
in bj****************************
Avg. episode reward:  -0.09
###################

running VI with gamma: 0.9  n_iters: 400000  theta: 0.01
runtime = 0.01 seconds
in bj****************************
Avg. episode reward:  -0.09
###################

running VI with gamma: 0.9  n_iters: 400000  theta: 0.001
runtime = 0.01 seconds
in bj****************************
Avg. episode reward:  -0.09
###################

running VI with g

In [ ]:
bj_vi.keys()

dict_keys([(0.9, 100000, 0.01), (0.9, 100000, 0.001), (0.9, 100000, 0.0001), (0.9, 100000, 1e-05), (0.9, 400000, 0.01), (0.9, 400000, 0.001), (0.9, 400000, 0.0001), (0.9, 400000, 1e-05), (0.9, 700000, 0.01), (0.9, 700000, 0.001), (0.9, 700000, 0.0001), (0.9, 700000, 1e-05), (0.9, 1000000, 0.01), (0.9, 1000000, 0.001), (0.9, 1000000, 0.0001), (0.9, 1000000, 1e-05), (0.95, 100000, 0.01), (0.95, 100000, 0.001), (0.95, 100000, 0.0001), (0.95, 100000, 1e-05), (0.95, 400000, 0.01), (0.95, 400000, 0.001), (0.95, 400000, 0.0001), (0.95, 400000, 1e-05), (0.95, 700000, 0.01), (0.95, 700000, 0.001), (0.95, 700000, 0.0001), (0.95, 700000, 1e-05), (0.95, 1000000, 0.01), (0.95, 1000000, 0.001), (0.95, 1000000, 0.0001), (0.95, 1000000, 1e-05), (0.99, 100000, 0.01), (0.99, 100000, 0.001), (0.99, 100000, 0.0001), (0.99, 100000, 1e-05), (0.99, 400000, 0.01), (0.99, 400000, 0.001), (0.99, 400000, 0.0001), (0.99, 400000, 1e-05), (0.99, 700000, 0.01), (0.99, 700000, 0.001), (0.99, 700000, 0.0001), (0.99, 7